#!/bin/sh

set -e

zmq_version="$1"

if [ "$zmq_version" == "" ]; then
  echo "usage: $0 VERSION"
  exit 1
fi

if [ "$AWS_ID" == "" ]; then
  echo "must set AWS_ID"
  exit 1
fi

if [ "$AWS_SECRET" == "" ]; then
  echo "must set AWS_SECRET"
  exit 1
fi

if [ "$S3_BUCKET" == "" ]; then
  echo "must set S3_BUCKET"
  exit 1
fi

basedir="$( cd -P "$( dirname "$0" )" && pwd )"

# make a temp directory
tempdir="$( mktemp -t zmq_XXXX )"
rm -rf $tempdir
mkdir -p $tempdir
cd $tempdir

# build and package zmq for heroku
vulcan build -v \
  -n zmq \
  -c "cd zmq-v${zmq_version} && ./configure --prefix=/app/vendor/zmq && make install" \
  -p /app/vendor/zmq \
  -s http://download.zeromq.org/zeromq-${zmq_version}.tar.gz \
  -o $tempdir/zmq-${zmq_version}.tgz

# upload nodejs to s3
$basedir/aws/s3 put $S3_BUCKET \
  zmq-${zmq_version}.tgz $tempdir/zmq-${zmq_version}.tgz

# generate manifest
$basedir/manifest zmq
